In [2]:
import numpy as np

In [16]:
x = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [17]:
#a
y = x[:, 2]
print(y)

[ 3  7 11 15]


In [18]:
#b
y = x[-1,:2]
print (y)

[13 14]


In [19]:
#c
y = x[:, [True, False, False, True]]; print(y)

[[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]


In [20]:
#d
y = x[0:2, 0:2]; print(y)

[[1 2]
 [5 6]]


In [21]:
#e
y = x[[0, 1, 2], [0, 1, 2]]; print(y)

[ 1  6 11]


In [22]:
#f
y = x[0]**2; print(y)

[ 1  4  9 16]


In [23]:
#g
y = x.max(axis=1); print(y)

[ 4  8 12 16]


In [24]:
#h
y = x[:2, :2]+x[:2,2:]; print(y)

[[ 4  6]
 [12 14]]


In [25]:
#i
y = x[:2, :3].T; print(y)

[[1 5]
 [2 6]
 [3 7]]


In [26]:
#j
y = x[:2, :3].reshape((3, 2)); print(y)

[[1 2]
 [3 5]
 [6 7]]


In [27]:
#k
y= x[:, :2].dot([1, 1]); print(y)

[ 3 11 19 27]


In [28]:
#l
y = x[:, :2].dot([[3, 0], [0, 2]]); print(y)

[[ 3  4]
 [15 12]
 [27 20]
 [39 28]]
